name: file_local_storage_example
description: "Demonstrates how to use the file_local_storage plugin."
publish_to: "none"

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_local_storage:
    path: ../

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
