name: file_local_storage
description: "A cross platform interface for storing user-generated files."
version: 1.0.1
repository: https://github.com/DaniilAlpha/file_local_storage/tree/master/file_local_storage

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  file_local_storage_impl: ^1.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
